name: vartur_assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  retrofit: '>=4.0.0 <5.0.0'
  dio: ^5.0.1
  dio_http2_adapter: ^2.0.0
  fpdart: ^0.5.0
  cached_network_image: ^3.2.3
  path_provider: ^2.0.14
  device_preview: ^1.1.0
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0' 
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
        - weight: 600
